definitions:
  main.SendMessageRequest:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /send:
    post:
      consumes:
      - application/json
      description: Send message to Kafka
      parameters:
      - description: Message request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.SendMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send message
      tags:
      - messages
swagger: "2.0"
