services:
  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    depends_on:
      - redis

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082

  cart-service:
    build: ./cart-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    depends_on:
      - redis

  kafka-producer:
    build: ./kafka-producer
    ports:
      - "8085:8085"
    environment:
      - PORT=8085

  kafka-consumer:
    build: ./kafka-consumer
    ports:
      - "8086:8086"
    environment:
      - PORT=8086

#  simple-service:
#    build: ./simple-service
#    ports:
#      - "8084:8084"
#    environment:
#      - PORT=8084

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
